name: build-docker-image

on: push

env:
  BOOTSTRAP_LICENSE: ${{ secrets.BOOTSTRAP_LICENSE }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout source
        uses: actions/checkout@v2

      - name: get image tag
        run: echo "IMAGE_TAG=$(git describe --always)" >> $GITHUB_ENV

      - name: load build config
        run: cat config.env >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            ghcr.io/singlestore-labs/singlestoredb-dev:${{ env.IMAGE_TAG }}
            ghcr.io/singlestore-labs/singlestoredb-dev:latest
          build-args: |
            BOOTSTRAP_LICENSE=${{ secrets.BOOTSTRAP_LICENSE }}
            RELEASE_CHANNEL=${{ env.RELEASE_CHANNEL }}
            SERVER_VERSION=${{ env.SERVER_VERSION }}
            CLIENT_VERSION=${{ env.CLIENT_VERSION }}
            STUDIO_VERSION=${{ env.STUDIO_VERSION }}
            TOOLBOX_VERSION=${{ env.TOOLBOX_VERSION }}
